#!/usr/bin/env bash
# Display information about subdomains
domain_func() {
	domain="$1"
	subdomain="$2"
	record=$(dig "$subdomain"."$domain" | grep -A1 'ANSWER SECTION:'| tr '\t' '\n' | tail -2 | tr '\n' ' ')
	echo "$subdomain $record" | awk '{print "The subdomain "$1" is a "$2" record and points to "$3""}'

}

if [ "$#" -eq 2 ]; then
	domain_func "$1" "$2"
else
        subdomains=("web-01" "web-02" "lb-01" "www" )
        for subdomain in "${subdomains[@]}"; do
	domain_func "$1" "$subdomain"
        done
fi
