#!/usr/bin/env bash
# install nginx on web-01

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html;

sudo nginx -i # ngnix configuration

sudo service nginx restart
sudo service ngix reload
