#!/usr/bin/env bash
# install nginx on web-01

sudo apt-get update
sudo apt-get install -y nginx

echo "server {
 listen 80 default_server;
 listen [::]:80 default_server;

 root /var/www/html;
 index index.html;

 location / {
  return 200 'Hello World!';
 }
}" > /etc/nginx/sites-available/default

sudo service nginx restart
sudo service ngix reload
