#!/usr/bin/env bash
# A bash script that configures your Nginx server and 
# redirects to another page.
redirect_301="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
redirect_301="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name_: $redirect_301" /etc/nginx/sites-available/default
sudo service nginx restart
