#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
apt-get update
apt-get install -y haproxy

cat <<EOL >> /etc/haproxy/haproxy.cfg
frontend myfrontend
  bind *:80
  default_backend myservers

backend myservers
  balance roundrobin
  server 404100-web-01 54.84.237.217
  server 404100-web-02 54.236.43.154
EOL
service haproxy start
