#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
apt-get update
apt-get install -y haproxy

cat <<EOL >> /etc/haproxy/haproxy.cfg
frontend myfrontend
  bind *:80
  default_backend myservers

backend myservers
  balance roundrobin
  server 405012-web-01 54.234.67.94
  server 405012-web-02 100.26.49.141
EOL
service haproxy start
