#!/usr/bin/env bash
# Find out what’s keeping your Ubuntu container’s Nginx
# installation from listening on port 80 
# all the server’s active IPv4 IPs configures a server to the above requirement
#  a Bash script with the minimum number of commands to automate the fix
sudo apt-get update
sudo apt-get install -y nginx
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
