#!/usr/bin/env bash
# This is a bash script that prints 10 lines with the content Best school
#+ using a while loop with an if statement

str=0

while ((str < 10))
do
        echo "Best School"
        ((str++))
	if [ $str -eq 9 ]
	then
		echo "Hi"
	fi
done
