#!/usr/bin/env bash
# This is a bash script that prints 10 lines with the content Best school
#+ using a while loop with an if statement

str=1

while ((str < 21))
do
	echo $str
	case "$str" in
		4)echo "bad luck from China";;
                9)echo "bad luck from Japan";;
                17)echo "bad luck from Italy";;
        esac
	((str++))
done
