#!/usr/bin/env bash
# This is a Bash script that configures an Ubuntu server with the
#+ below requirements.

#+ Requirements:

#+localhost resolves to 127.0.0.2
#+facebook.com resolves to 8.8.8.8.
# Update the operating system packages.
#sudo apt update
#sudo apt upgrade

# Install the necessary networking tools.
#sudo apt install net-tools

# Configure the hosts file to resolve localhost to 127.0.0.2.
#echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts

# Configure the hosts file to resolve facebook.com to 8.8.8.8.
#echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts

# Restart the networking service.
#sudo service networking restart
cp /etc/hosts ~/hosts.new
sed -i 's/.*localhost$/127.0.0.2	localhost\n8.8.8.8 facebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts

